### ISSUE TITLE
Redirection of archived project pages

### ISSUE THREAD

**Issue by tasmo** [prototypefund/demo-week-runde8#14]
Projects need to be redirected from here (https://demoweek.prototypefund.de/) to protoypefund/demo-week-2020 (https://archive.demoweek.prototypefund.de/).

**Comment by abrain** [comment]
Seems this was fixed with https://github.com/prototypefund/demo-week-runde8/commit/be346fd3684d92221bfc79f0bbb0a610139355f5 👍🏻
